#!/usr/bin/env python3
"""Render matching rules from Markdown using the shared document renderer."""
from pathlib import Path
import json
from build_extraction_rules import Renderer, document_html, discover_rules

ROOT = Path(__file__).resolve().parent.parent
DOCUMENTS = (
    ('index', '인덱스', '지역·분석법 데이터와 매칭 조건.'),
    ('location', '지역 매칭', '시료의 지역 표기와 정식 지점·좌표 연결.'),
    ('analysis-method', '분석법 매칭', '분석물질과 시험방법 코드의 공통 매칭.'),
)


def build_matching_rules(root=ROOT):
    root = Path(root).resolve()
    folder = root / 'docs' / 'matching-rules'
    if not (folder / 'index.md').is_file():
        return False
    page_map = {folder / (slug + '.md'): 'rist-matching-' + slug
                for slug, _, _ in DOCUMENTS}
    for source in (root / 'docs' / 'db-lists').glob('*.md'):
        page_map[source] = ('rist-db-lists-index' if source.stem == 'index'
                            else 'rist-db-list-' + source.stem)
    page_map.update({source: 'extraction-rule-' + source.stem for source in discover_rules(root)})
    obsolete = root / 'pages' / 'rist-matching-applicability.html'
    obsolete.unlink(missing_ok=True)
    pages = []
    for slug, title, summary in DOCUMENTS:
        source = folder / (slug + '.md')
        metadata, content = Renderer(root, source, page_map).render(source.read_text(encoding='utf-8'))
        document = document_html(root, source, title, metadata, content)
        document = document.replace('Generated extraction-rule document.', 'Generated matching-rule document.')
        document = document.replace('RIST · EXTRACTION RULES', 'RIST · MATCHING RULES')
        download_name = ('매칭 규칙' if slug == 'index' else title) + '.md'
        document = document.replace('download="' + source.name + '"', 'download="' + download_name + '"')
        document = document.replace('class="extraction-download-label">' + source.name + '</span>', 'class="extraction-download-label">' + download_name + '</span>')
        document = document.replace('title="' + source.name + ' 다운로드"', 'title="' + download_name + ' 다운로드"')
        document = document.replace('aria-label="' + source.name + ' 다운로드"', 'aria-label="' + download_name + ' 다운로드"')
        page_id = page_map[source]
        destination = root / 'pages' / (page_id + '.html')
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(document, encoding='utf-8')
        pages.append({'id': page_id, 'title': title, 'summary': summary,
                      'src': 'pages/' + page_id + '.html', 'width': 1280,
                      'autoHeight': True, 'kind': '매칭 규칙', 'hideEmptyDescription': True})
    target = root / 'data' / 'matching-rules.js'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text('// Generated by scripts/build_matching_rules.py.\nwindow.MOCKUP_VIEWER_MATCHING_RULE_PAGES = ' +
                      json.dumps(pages, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
    return True


if __name__ == '__main__':
    build_matching_rules()
