#!/usr/bin/env python3
"""Build the nine returned DB lists and their index from Markdown."""
from pathlib import Path
from html import escape
from urllib.parse import quote
import json

from build_extraction_rules import Renderer
from build_schema import STYLE
from build_policies import DOWNLOAD_ICON

ROOT = Path(__file__).resolve().parent.parent
DOCUMENTS = (
    ('index', 'DB 리스트'), ('category', '구분'), ('medium', '매체'),
    ('person', '담당자'), ('institution', '분석 기관'), ('location', '지역·관측 지점'),
    ('base', 'BASE'), ('sampling-method', '채취법'), ('analysis-method', '분석법'), ('unit', '단위'),
)
LIST_STYLE = STYLE + '''
    .db-lists-document .extraction-catalog { width: 100%; }
    .db-lists-document .extraction-catalog th:nth-child(1) { width: 19%; }
    .db-lists-document .extraction-catalog th:nth-child(2) { width: 20%; }
    .db-lists-document .extraction-catalog th:nth-child(3) { width: 9%; }
    .db-lists-document .extraction-catalog th:nth-child(4) { width: 40%; }
    .db-lists-document .extraction-catalog th:nth-child(5) { width: 12%; }
    .db-lists-document code { white-space: pre-wrap; }
'''

def document_html(source, title, metadata, content):
    details = []
    for key, label in [('version', '버전'), ('created_at', '작성일'), ('updated_at', '수정일')]:
        if value := metadata.get(key):
            details.append('<span>' + label + ' ' + escape(value.replace('-', '/') if key.endswith('_at') else value) + '</span>')
    filename = title + '.md'
    href = '../docs/db-lists/' + quote(source.name)
    return ('<!doctype html>\n<!-- Generated by scripts/build_db_lists.py. Edit docs/db-lists Markdown. -->\n'
        '<html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">'
        '<title>' + escape(title) + '</title><style>' + LIST_STYLE + '</style></head><body>'
        '<main class="policy-document schema-document db-lists-document" data-document-root>'
        '<header class="policy-header has-labeled-download"><div class="document-header-main">'
        '<div class="policy-kicker">RIST · DB LISTS</div><h1>' + escape(title) + '</h1>'
        '<div class="schema-meta">' + ''.join(details) + '</div></div>'
        '<div class="document-download-row"><span class="document-download-label">' + escape(filename) + '</span>'
        '<a data-document-download href="' + href + '" download="' + escape(filename, quote=True) + '" '
        'class="document-download" title="MD 다운로드" aria-label="' + escape(filename, quote=True) + ' 다운로드">'
        + DOWNLOAD_ICON + '</a></div></header><div class="policy-sections">' + content + '</div></main></body></html>\n')

def build_db_lists(root=ROOT):
    root = Path(root).resolve()
    folder = root / 'docs' / 'db-lists'
    if not (folder / 'index.md').exists():
        return False
    page_map = {folder / (slug + '.md'): ('rist-db-lists-index' if slug == 'index' else 'rist-db-list-' + slug) for slug, _ in DOCUMENTS}
    # Validate every document before writing any generated files.
    pages, rendered = [], {}
    for slug, title in DOCUMENTS:
        source = folder / (slug + '.md')
        if not source.is_file() or not source.resolve().is_relative_to(folder.resolve()):
            raise ValueError('Missing or out-of-tree DB list: ' + slug)
        metadata, content = Renderer(root, source, page_map).render(source.read_text(encoding='utf-8'))
        page_id = page_map[source]
        rendered[page_id] = document_html(source, title, metadata, content)
        pages.append({'id': page_id, 'title': '인덱스' if slug == 'index' else title,
                      'src': 'pages/' + page_id + '.html', 'width': 1280, 'autoHeight': True,
                      'summary': '', 'hideEmptyDescription': True})
    (root / 'pages').mkdir(exist_ok=True)
    (root / 'data').mkdir(exist_ok=True)
    for page_id, html in rendered.items():
        (root / 'pages' / (page_id + '.html')).write_text(html, encoding='utf-8')
    (root / 'data' / 'db-lists.js').write_text(
        '// Generated by scripts/build_db_lists.py.\nwindow.MOCKUP_VIEWER_DB_LIST_PAGES = '
        + json.dumps(pages, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
    return True

if __name__ == '__main__':
    if build_db_lists():
        print('Built DB list index, nine documents, and navigation data.')
